"""initialize models

Revision ID: 624481091cfb
Revises: 
Create Date: 2017-11-23 22:12:32.342794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624481091cfb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_rawid', sa.Text(), nullable=False),
    sa.Column('_version', sa.Text(), nullable=False),
    sa.Column('arxiv_id', sa.Text(), nullable=False),
    sa.Column('arxiv_comment', sa.Text(), nullable=True),
    sa.Column('arxiv_primary_category', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('author_detail', sa.Text(), nullable=False),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('links', sa.Text(), nullable=True),
    sa.Column('published', sa.DateTime(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_papers')),
    sa.UniqueConstraint('arxiv_id', name=op.f('uq_papers_arxiv_id'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('name', name=op.f('uq_users_name'))
    )
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_pages_creator_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pages')),
    sa.UniqueConstraint('name', name=op.f('uq_pages_name'))
    )
    op.create_table('paper_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_paper_ratings_paper_id_papers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_ratings'))
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('unique_name', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_tags_creator_id_users')),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_tags_paper_id_papers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('unique_name', name=op.f('uq_tags_unique_name'))
    )
    op.create_table('tips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_tips_creator_id_users')),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_tips_paper_id_papers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tips'))
    )
    op.create_table('user_paper_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('unique_name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_user_paper_ratings_creator_id_users')),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_user_paper_ratings_paper_id_papers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_paper_ratings')),
    sa.UniqueConstraint('unique_name', name=op.f('uq_user_paper_ratings_unique_name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_paper_ratings')
    op.drop_table('tips')
    op.drop_table('tags')
    op.drop_table('paper_ratings')
    op.drop_table('pages')
    op.drop_table('users')
    op.drop_table('papers')
    # ### end Alembic commands ###
